#pragma once

/* key matrix size */
#define MATRIX_ROWS 5
#define MATRIX_COLS 4

#define MATRIX_ROW_PINS { D0, D1, D4, D7, C6 }
#define MATRIX_COL_PINS { F4, F5, F6, F7 }

#define DIODE_DIRECTION COL2ROW

#define DEBOUNCE 2

#define WS2812_DI_PIN B6
#define RGB_MATRIX_LED_COUNT 12
#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 17
#define RGBLIGHT_VAL_STEP 17
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0
